### ISSUE TITLE
Unable to revise the security permissions via the Azure application registration

### ISSUE THREAD

**Issue by joviledog** [microsoftgraph/aspnet-snippets-sample#23]
Right now, the readme file of this sample shows how to grant permissions for a specific user to use the Graph API.  But if my application is designed so everyone in the O365 tenant could use that, then the current registration scheme is not scalable since I can't register a different application for each user. I need to use the Azure portal:  https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps  UI to create an application by saving the tenant global application ID and secret.  Then I recognized that there are a bunch of delegated permissions granted on a per-user basis (14 of them through user consents) so I use the Azure UI instead of https://apps.dev.microsoft.com/ to grant a single App application for all users in the same tenant.

However, when I did that and trying to run the application to login, I got back a response error:
Sign In

Sorry, but we’re having trouble signing you in. 
We received a bad request.

Additional technical information:
Correlation ID: f665b12b-999a-4110-ba1c-8b0c758df1d0
Timestamp: 2017-04-24 19:06:15Z
AADSTS70001: Application '5a8735c1-be64-496c-88ac-f0a1694021b4' is not supported for this API version.

I captured what the user consent permissions were granted for, and they are:
Read all users' basic profiles 
View users' email address 
View users' basic profile 
Access user's data anytime 
Sign in and read user profile 
Read and write access to user profile 
Sign users in 
Send mail as a user 
Have full access to user calendars 
Read and write access to user mail 
Have full access to user files 
Access directory as the signed in user 
Read and write all users' full profiles 
Read and write all groups 

Perhaps there is a way to provide a way to register the application via this Azure interface so I could get the permissions granted properly.

**Comment by jamescro** [comment]
This sample uses the MSAL library, which authenticates users by using dynamic consent. When each users signs in to the app for the first time, that user is prompted to consent to the permissions required for the app to run. This has to happen on a per-user basis, but you don't need to register a new client for each user.

You can also consider app-only permissions if you want an admin to consent for an entire organization. You can read about the differences between the two permission models here: https://msdn.microsoft.com/en-us/Library/Azure/Ad/Graph/howto/azure-ad-graph-api-permission-scopes
When you register a client by using the Azure portal, you are required to use v1 auth, which assigns delegated (or app-only) permissions statically. That's why you're getting the error stating that your client isn't supported for the API version. The v1 endpoint supports only clients that are registered in the Azure portal.
Does v2 auth not work for you? You can read more about this decision point here: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-limitations

**Comment by jamescro** [comment]
Closing for now. Please let us know if you're having any problem with this sample specifically.
