### ISSUE TITLE
Question: Turning off Implicit Flow

### ISSUE THREAD

**Issue by RyanTaite** [microsoftgraph/aspnet-snippets-sample#33]
Wanting to make a new Web App using MSAL, the v2 Endpoint, and MS Graph I've learned that I want to avoid `Implicit Flow` when possible and instead opt for `Authorization Code Flow` for security.

This sample explicitly states:
> Make sure the **Allow Implicit Flow** check box is selected

In order to use `Hybrid Flow`

Turning off `Implicit Flow` returns an error saying
> Error.
An error occurred while processing your request.
unsupported_response_type

**My question:** Will there be an example showing how to do a similar sample without using `Implicit Flow`? More specifically an example using `Authorization Code Flow`?

*Edit: Reworded question*

**Comment by jasonjoh** [comment]
Realize this is an old post, but wanted to answer it anyway :).

OWIN is the bit that requires Implicit Flow. It needs to get an identity token back from the authorization request in order to fill in all the user context stuff that OWIN manages. The access token acquisition is all done via authorization code flow.

Azure has improved this since this sample was written - you can now select what kind of tokens Implicit Flow will return. You can just enable identity tokens and this should work.

More info: [Microsoft identity platform and Implicit grant flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-the-sign-in-request)
