### ISSUE TITLE
MSAL.NET 3 - breaks these samples?

### ISSUE THREAD

**Issue by dblancard** [microsoftgraph/aspnet-snippets-sample#54]
Not sure if this repo is still actively being worked on, but:

I just cloned this repo, and then corrected 8 or so build errors because of errors related to deprecated calls  moving from MSAL.NET 2.0 to 3.0...

It builds fine, now, but the app immediately aborts after authentication with a error I am getting used to seeing:  

**Error.
An error occurred while processing your request.
See https://aka.ms/msal-net-3-breaking-changes**

is anyone using MSAL.NET 3.0 successfully with these snippets?

Dave

**Comment by jasonjoh** [comment]
@dblancard I'm going to be updating this to ASP.NET Core and Microsoft.Identity.Web (the preview library that wraps MSAL for ASP.NET Core), so this will actually be using MSAL 4.x. In order to update this sample as it is right now, you'd need to follow MSAL's guidance for updating all the auth code.

**Comment by jasonjoh** [comment]
Migration to ASP.NET Core is live. Closing this issue.
