### ISSUE TITLE
Why do we have both OAuth2CodeRedeemerMiddleware and an AuthorizationCodeReceived handler in Startup.Auth.cs ?

### ISSUE THREAD

**Issue by guilmori** [microsoftgraph/aspnet-snippets-sample#8]
Why do we have both OAuth2CodeRedeemerMiddleware and an AuthorizationCodeReceived handler in Startup.Auth.cs ?

What is the role of each one ?

**Comment by DianeD** [comment]
Hi @guilmori . This sample supports incremental consent. It prompts users to consent to an initial set of permission scopes during sign in, and then admin scopes later. AuthorizationCodeReceived handles the initial token acquisition. OAuth2CodeRedeemerMiddleware is custom middleware that was added to support incremental consent because "the standard collection of OWIN middlewares doesn't include anything that can be used for redeeming an authorization code for access and refresh tokens outside of a sign in flow". Please see [https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-v2](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-v2) for more information.

**Comment by guilmori** [comment]
Got it, thanks !

**Comment by guilmori** [comment]
For the incremental consent, why using an owin middleware instead of using an redirectUri to an specific action that would processed the admin consent response ?

I don't like the fact that the middleware 'trigger ' is to have a 'code' in query string. That is too implicit.

**Comment by DianeD** [comment]
Hi @guilmori . I'd recommend opening this issue in the Azure sample repo. They can better discuss implementation details and options. 

Their readme does say that "the custom middleware is provided only as an example, and it has numerous limitations ... that limit its applicability outside of this scenario" so you should be able to implement something that suits your requirements better.
